spring.application.name=OrbitWatch
server.port=8080

# Profil actif
spring.profiles.active=dev

# JPA / PostgreSQL (prod)
# Ces valeurs sont surchargees par application-dev.properties en mode dev
spring.datasource.url=jdbc:postgresql://localhost:5432/orbitwatch
spring.datasource.username=orbitwatch
spring.datasource.password=orbitwatch
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
