# Profil DEV — PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/orbitwatch
spring.datasource.username=orbitwatch
spring.datasource.password=orbitwatch
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

